spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.31.86.56:9092
      function:
        definition: calculateNumberOfOperations
      bindings:
        calculateNumberOfOperations-in-0:
          destination: trades
        calculateNumberOfOperations-out-0:
          destination: numberOfOperations

logging.file.path: /home/logs
