logging.file.path: /home/logs
spring:
  kafka:
    bootstrap-servers: 172.31.86.56:9092
    producer:
      properties.spring.json.add.type.headers: false
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
