server.port: 8081
spring.main.allow-circular-references: true
spring:
  kafka:
    consumer:
      properties:
        max.poll.records: 1
  cloud:
    stream:
      kafka:
        binder:
          brokers: ip-172-31-86-56.ec2.internal:9092
      function:
        definition: sendVolumeEventsToClient;sendTradeEventsToClient
      bindings:
        sendEventsToClient-in-0:
          destination: numberOfOperations
        sendTradeEventsToClient-in-0:
          destination: trades

logging.file.path: /home/logs



